---
title: "Data_viz"
author: "Brandon"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Visualization and Exploratory Analysis


```{r}
install.packages("ggplot2")
install.packages("pheatmap")

library(ggplot2)
library(pheatmap)

```

## Create a random matrix and import the intergrated dataset

```{r pressure, echo=FALSE}
df <- matrix(rnorm(1000),nrow=100)
iris <- iris
```

```{r}
pheatmap(df)
pheatmap(iris[1:4])
```
#plot()

https://r-coder.com/plot-r/

```{r}
plot(iris[,2:3])
```

```{r}
plot(iris)
```
```{r}
hist(iris[,2])
```

```{r}
boxplot(Petal.Length~Species,data=iris)
```

# Label, theme and par

```{r}

plot(iris[,2:3] ,
     main="The Iris Scatter Plot",
     ylab="Sepal Length",
     xlab="Sepal Width",
     cex = 3,
     xlim = c(1, 5),
     ylim = c(1,7)
     )

```

#ggplot


#barplot

#scatter


#coorplot
https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html


```{r}
library(corrplot)
x <- cor(iris[1:4])

corrplot(x, method = "circle")

```


#performance Analysis

```{r}
library(PerformanceAnalytics)

chart.Correlation(
  iris[1:4],
  histogram = TRUE,
  method = c("pearson")
)
```







